DroneMainAdmin/Controllers/TeamListController.cs
using DroneMainAdmin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Newtonsoft.Json;
using DroneMainAdmin.Models;
using System.Text;
using System.Data.Entity.Validation;
using System.Web.UI.WebControls;
using System.Web.UI;
using System.IO;

namespace DroneMainAdmin.Controllers
{
    public class TeamListController : Controller
    {
        private DroneDBEntities dbe = new DroneDBEntities();
        // GET: /User/
        [Authorize]
        [HttpGet]
        public ActionResult Index()
        {
            if(User.Identity.IsAuthenticated)
            {
               // ViewBag.Message = "Welcome to administation panel";
            }
           
            return View();

        }

        // GET: /User/Details/5
        public ActionResult Details(int id = 0)
        {
            User user = dbe.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        [HttpGet]
        public JsonResult GetTeams()
        {
            bool status = false;
            using (DroneDBEntities dc = new DroneDBEntities())
            {
                List<User> userList = dc.Users.ToList<User>();
                ViewBag.Message = "Data Loading..";
                //var team = dc.Users.OrderBy(a => a.FirstName).ToList();
               // return Json(new { success = status, messgae = userList }, JsonRequestBehavior.AllowGet);
                return Json(userList, JsonRequestBehavior.AllowGet);
            }
        }

        [Authorize]
        [HttpGet]//Get all Annocement
        public JsonResult GetAnnoucement()
        {
            bool status = false;
            using (DroneDBEntities dc = new DroneDBEntities())
            {
                List<Annoucement> annouceList = dc.Annoucements.ToList<Annoucement>();
                return Json(annouceList, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult PostAnnocement(DroneMainAdmin.Models.Annoucement ano)
        {

            return View();
        }

        //[Authorize]
        //[HttpPost]
        //public ActionResult PostAnnocement(DroneMainAdmin.Models.Annoucement anno)
        //{
        //    return View();
        //}
        // POST: /User/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(User user, string Command)
        {
            if (ModelState.IsValid)
            {
                dbe.Users.Add(user);
                dbe.SaveChanges();
                TempData["Msg"] = "Data has been saved succeessfully";
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: /User/Edit/5
        [HttpGet]
        public ActionResult Edit([Bind(Exclude = "ConfirmPassword")]DroneMainAdmin.Models.User user, int id)
        {
            DroneDBEntities drop = new DroneDBEntities();
            if (User.Identity.IsAuthenticated)
            {
                string username = User.Identity.Name;
                var v = drop.Users.Where(a => a.UserID == id).FirstOrDefault();
                try
                {
                    var adminchk = drop.Users.Where(a => a.EmailID == username).FirstOrDefault();
                   if (v != null && adminchk.AdminType == true)
                    {
                        string selected = (from sub in drop.Users
                                           where sub.UserID == id
                                           select sub.CountryName).FirstOrDefault();
                        ViewBag.SelectValue = new SelectList(drop.countries, "name", "name", selected);
                        string stateselect = (from sub in drop.Users
                                              where sub.UserID == id
                                              select sub.Provinance).FirstOrDefault();
                        ViewBag.StateSelect = new SelectList(drop.states, "name", "name", stateselect);
                        ViewBag.DateSet = (from sub in drop.Users
                                           where sub.UserID == id
                                           select sub.DateOfBirth).FirstOrDefault();
                        user = dbe.Users.Find(id);
                    }
                   else
                    {
                        ViewBag.Message = "You are Not Authorize for View This Page";
                        return RedirectToAction("Index");
                    }
                }
                catch(Exception ex)
                {
                    ViewBag.Message = "You are Not Authorize for View This Page";
                    return RedirectToAction("Index");

                }
            }
            else
            {
                ViewBag.Message = "You are Not Authorize for View This Page";
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // POST: /User/Edit/5

        [Authorize] 
        [ActionName("Edit")]
        [HttpPost]
        public ActionResult Edit([Bind(Exclude = "ConfirmPassword")]DroneMainAdmin.Models.User user)
        {
            bool status = false;
            string message = "";
            if (User.Identity.IsAuthenticated)
            {
                if (!ModelState.IsValid)
                {
                    using (DroneDBEntities db = new DroneDBEntities())
                    {
                        string username = User.Identity.Name;
                        var v = dbe.Users.Where(a => a.UserID == user.UserID).FirstOrDefault();
                        try
                        {
                            var adminchk = dbe.Users.Where(a => a.EmailID == username).FirstOrDefault();
                            if (v != null && adminchk.AdminType == true)
                            { 
                                db.Configuration.ValidateOnSaveEnabled = false; // Avoid Confirmation password does not match on save changes
                                v.FirstName = user.FirstName;
                                v.MiddleName = user.MiddleName;
                                v.LastName = user.LastName;
                                v.EmailID = user.EmailID;
                                v.ContactNo = user.ContactNo;
                                v.TeamName = user.TeamName;
                                if (user.Password.Length <= 42)
                                {
                                    v.Password = Crypto.Hash(user.Password);
                                }
                                // v.Password = user.Password;
                                //  v.ConfirmPassword = user.ConfirmPassword;
                                // v.DateOfBirth = user.DateOfBirth;
                                if (user.IsEmailVerified)
                                {
                                    v.IsEmailVerified = true;
                                }
                                else
                                {
                                    v.IsEmailVerified = false;
                                }
                                v.CountryName = user.CountryName;
                                if (user.SubEmail)
                                {
                                    v.SubEmail = true;
                                }
                                else
                                {
                                    v.SubEmail = false;
                                }
                                v.Decscript = user.Decscript;
                                if (user.AdminType == true)
                                {
                                    v.AdminType = true;
                                }
                                else
                                {
                                    v.AdminType = false;
                                }
                                try
                                {
                                    //  db.Users.Add(v);
                                    // db.Entry(user).State = System.Data.Entity.EntityState.Modified;
                                    db.Entry(v).State = System.Data.Entity.EntityState.Modified;
                                    db.SaveChanges();
                                }
                                catch (DbEntityValidationException ex)
                                {
                                    StringBuilder sb = new StringBuilder();
                                    foreach (var eve in ex.EntityValidationErrors)
                                    {
                                        sb.AppendLine(string.Format("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                                                                        eve.Entry.Entity.GetType().Name,
                                                                        eve.Entry.State));
                                        foreach (var ve in eve.ValidationErrors)
                                        {
                                            sb.AppendLine(string.Format("- Property: \"{0}\", Error: \"{1}\"",
                                                                        ve.PropertyName,
                                                                        ve.ErrorMessage));
                                        }
                                    }
                                    message = "Error Message  :" + ex;

                                }
                                status = true;
                                ViewBag.Message = "User Profile is Succesfully Updated";
                            }
                            else

DroneMainAdmin/Views/TeamList/AddOrEdit.cshtml
@model DroneMainAdmin.Models.User
<h2 align="center">Detaile Form</h2>
@using (Html.BeginForm("AddOrEdit", "TeamList", FormMethod.Post, new { id = "dialog-alert" }))
{
    if (Model != null && Model.UserID > 0)
    {
        @Html.HiddenFor(a => a.UserID)
    }
    <div class="col-sm-12">
        <div class="contact-area" style="background-color:black">
            <div class="contact-form" style="margin-top:32px">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.UserID)

                <div class="form-group">
                    @*@Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-4" })*@
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", @placeholder = "First Name" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "notifyjs-center" })
                    </div>
                </div>

                <div class="form-group">
                    <br />
                    @*@Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "control-label col-md-4" })*@
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Middle Name" } })
                        @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <br />
                    @*@Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-4" })*@
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Last Name" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <br />
                    @*@Html.LabelFor(model => model.EmailID, htmlAttributes: new { @class = "control-label col-md-4" })*@
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.EmailID, new { htmlAttributes = new { @class = "form-control", @placeholder = "Eamil ID" } })
                        @Html.ValidationMessageFor(model => model.EmailID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <br />
                    @*@Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "control-label col-md-3 glyphicon glyphicon-phone-alt" })*@
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { type = "tel", @class = "intl-tel-input form-control", @id = "mobile-number", @placeholder = "eg. +91 9876543210" } })
                        <div class="col-md-11">
                            <span id="valid-msg" class="alert alert-success glyphicon glyphicon glyphicon-ok hide" role="alert">Valid</span>
                            <span id="error-msg" class="alert alert-danger glyphicon glyphicon glyphicon-exclamation-sign hide" role="alert">Invalid Number</span>
                        </div>
                    </div>
                </div><br />
                <div class="form-group">
                    <br />
                    @*@Html.LabelFor(model => model.TeamName, htmlAttributes: new { @class = "control-label col-md-4" })*@
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.TeamName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Team Name" } })
                        @Html.ValidationMessageFor(model => model.TeamName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <br />
                    @*@Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-4" })*@
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <br />
                    @*@Html.LabelFor(model => model.CountryName, htmlAttributes: new { @class = "control-label col-md-4" })*@
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.AddresL, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Your Address Here" } })
                        @Html.ValidationMessageFor(model => model.AddresL, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <br />
                    <div class="col-md-12">
                        @*@Html.EditorFor(model => model.CountryName, new { htmlAttributes = new { @class = "form-control", @placeholder = "eg. India" } })*@
                        @Html.DropDownListFor(model => model.CountryName, ViewBag.SelectValue as SelectList, "Select Country", new { @id = "idcountry", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CountryName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <br />
                    @*@Html.LabelFor(model => model.CountryName, htmlAttributes: new { @class = "control-label col-md-4" })*@
                    <div class="col-md-12">
                        @*<select id="St" class="form-control">

                            </select>*@
                        @if (ViewBag.StateSelect != null)
                        {
                            @Html.DropDownListFor(model => model.Provinance, ViewBag.StateSelect as SelectList, "Select State", new { @id = "state_id", @class = "form-control", @placeholder = "State/Provinance Name" })
                        }

                    </div>
                </div>
                <div class="form-group">
                    <br />
                    @*@Html.LabelFor(model => model.CountryName, htmlAttributes: new { @class = "control-label col-md-4" })*@
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control", @placeholder = "City Name" } })
                        @*@Html.DropDownListFor(model => model.CityName, ViewBag.CountryName as SelectList, "-- Select Country --", new { id = "idcountry", @class = "form-control" })*@
                        @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <br />
                    @*@Html.LabelFor(model => model.CountryName, htmlAttributes: new { @class = "control-label col-md-4" })*@
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control", @placeholder = "Street Name" } })
                        @*@Html.DropDownListFor(model => model.CityName, ViewBag.CountryName as SelectList, "-- Select Country --", new { id = "idcountry", @class = "form-control" })*@
                        @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <br />
                    @*@Html.LabelFor(model => model.CountryName, htmlAttributes: new { @class = "control-label col-md-4" })*@
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Pincode, new { htmlAttributes = new { @class = "form-control", @placeholder = "Zip/Pincode" } })
                        @*@Html.DropDownListFor(model => model.CityName, ViewBag.CountryName as SelectList, "-- Select Country --", new { id = "idcountry", @class = "form-control" })*@
                        @Html.ValidationMessageFor(model => model.Pincode, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <br />
                    @*@Html.LabelFor(model => model.Decscript, htmlAttributes: new { @class = "control-label col-md-4" })*@
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Decscript, new { htmlAttributes = new { @class = "form-control", @placeholder = "Brief Intoduction About Self/Team", @cols = "20", @rows = "2" } })
                        @Html.ValidationMessageFor(model => model.Decscript, "", new { @class = "" })
                    </div>
                </div>

                <div class="col-md-1">
                    <br />
                    <label class="control-label checkbox" style="color:white">Accept T&C</label>
                    @*@Html.LabelFor(model => model.TermsAccepted, htmlAttributes: new { @class = "control-label checkbox", @style = "color:white" })*@
                    @Html.EditorFor(model => model.TermsAccepted)
                    @Html.ValidationMessageFor(model => model.TermsAccepted, "", new { @class = "text-danger" })

                </div>
                <div class="col-md-2" style="margin-left:-104px;padding-left:120px;">
                    <br />
                    <label class="control-label checkbox" style="color:white;">Subscribe Letter</label>
                    @*@Html.LabelFor(model => model.SubEmail, htmlAttributes: new { @class = "control-label checkbox", @style = "color:white" })*@
                    @Html.EditorFor(model => model.SubEmail)
                    @Html.ValidationMessageFor(model => model.SubEmail, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-offset-2 col-md-1">
                    <br />
                    <label class="control-label checkbox" style="color:white;">Admin Authorize</label>
                    @*@Html.LabelFor(model => model.TermsAccepted, htmlAttributes: new { @class = "control-label checkbox", @style = "color:white" })*@
                    @Html.EditorFor(model => model.AdminType)
                    @Html.ValidationMessageFor(model => model.AdminType, "", new { @class = "text-danger" })

                </div>

                <div class="form-group">
                    <br />
                    <div class="col-md-8 col-sm-8" style="margin-bottom:25px;">
                        <input type="submit" value="SUBMIT" class="btn btn-lg btn-success" />
                    </div>
                    <div class="col-md-8 col-sm-8" style="margin-bottom:25px;">
                        <button id="cancel" class="btn btn-lg btn-danger">Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

}
@section Scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="@Url.Content("/Scripts/intlTelInput.js")"></script>
    <script type="text/javascript">
                var telInput = $("#mobile-number"),
            errorMsg = $("#error-msg"),
            validMsg = $("#valid-msg");
                //initialise plugin
                telInput.intlTelInput({
                    utilsScript: "~/Scripts/utils.js"
                });

                //on blur: validate
                telInput.blur(function () {
                    if ($.trim(telInput.val())) {
                        if (telInput.intlTelInput("isValidNumber")) {
                            validMsg.removeClass("hide");
                            errorMsg.addClass('hide');
                        } else {
                            telInput.addClass("error");
                            errorMsg.removeClass("hide");
                            validMsg.addClass('hide');

                        }
                    }
                });

                //on Keydown: reset
                telInput.keydown(function () {
                    telInput.removeClass("error");
                    errorMsg.addClass("hide");
                    validMsg.addClass("hide")
                });

    </script>
    <script>
        $(document).ready(function () {
            $("#idcountry").change(function () {
                $.get("/User/GetStateById", { ID: $("#idcountry").val() }, function (data) {
                    $("#state_id").empty();
                    $.each(data, function (index, row) {
                        $("#state_id").append("<option value='" + row.state_id + "'>" + row.name + "</option>")
                    });
                })
            });
        });
    </script>
    <script>
        $(document).ready(function () {
            $('#cancel').change(function () {
                $(this).dialog('close');
            })
        })
    </script>
    }
    @*<script type="text/javascript">
            $("#mobile-number").intlTelInput();
        </script>*@
    
    

DroneMainAdmin/Views/TeamList/Delete.cshtml
@model DroneMainAdmin.Models.User

<h2>Delete Member</h2>
@using (Html.BeginForm("delete", "TeamList", FormMethod.Post, new { id = "popupForm" }))
{
    @Html.HiddenFor(a => a.UserID)

    <div class="form-group">
        <label>First Name</label>
        <p>@Model.FirstName</p>
    </div>

    <div class="form-group">
        <label>Middle Name</label>
        <p>@Model.MiddleName</p>
    </div>

    <div class="form-group">
        <label>Last Name</label>
        <p>@Model.LastName</p>
    </div>

    <div class="form-group">
        <label>Email ID</label>
        <p>@Model.EmailID</p>
    </div>

    <div class="form-group">
        <label>Team Name</label>
        <p>@Model.TeamName</p>
    </div>

    <div class="form-group">
        <label>Estd. Date</label>
        <p>@Model.DateOfBirth</p>
    </div>

    <div class="form-group">
        <label>Contact No.</label>
        <p>@Model.CountryName</p>
    </div>

    <div class="form-group">
        <label>Country</label>
        <p>@Model.CountryName</p>
    </div>

    <div class="form-group">
        <label>Description</label>
        <p>@Model.Decscript</p>
    </div>

    <div class="form-group">
        <label>Subscribe Email</label>
        <p>@Model.SubEmail</p>
    </div>

    <div class="form-group">
        <label>Verified</label>
        <p>@Model.IsEmailVerified</p>
    </div>

    <div class="form-group">
        <label>Is Admin</label>
        <p>@Model.AdminType</p>
    </div>

    <div class="form-group">
        <div>
            <input type="submit" value="Delete" class="btn btn-sm btn-warning" />
        </div>
    </div>
}

DroneMainAdmin/Views/TeamList/Save.cshtml
@model DroneMainAdmin.Models.User
<h2>Save</h2>
@using (Html.BeginForm("save", "TeamList", FormMethod.Post, new { id = "popupForm" }))
{
    if (Model != null && Model.UserID > 0)
    {
        @Html.HiddenFor(a => a.UserID)
    }

    <div class="form-group">
        <label>First Name</label>
        @Html.EditorFor(a => a.FirstName, new { @class = "form-group", @placeholder = "First Name" })
        @Html.ValidationMessageFor(a => a.FirstName, "", new { @class = "text-danger" }))
    </div>
    <div class="form-group">
        <label>Middle Name</label>
        @Html.EditorFor(a => a.MiddleName, new { @class = "form-group", @placeholder = "Middle Name" })
        @Html.ValidationMessageFor(a => a.MiddleName, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label>Last Name</label>
        @Html.EditorFor(a => a.LastName, new { @class = "form-group", @placeholder = "Last Name" })
        @Html.ValidationMessageFor(a => a.LastName, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label>Email</label>
        @Html.EditorFor(a => a.EmailID, new { @class = "form-group", @placeholder = "Email ID" })
        @Html.ValidationMessageFor(a => a.EmailID, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label>Contact No.</label>
        @Html.EditorFor(a => a.ContactNo, new { @class = "form-group", @placeholder = "eg. +91 9876543210" })
        @Html.ValidationMessageFor(a => a.ContactNo, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label>Team Name</label>
        @Html.EditorFor(a => a.TeamName, new { @class = "form-group", @placeholder = "Team Name" })
        @Html.ValidationMessageFor(a => a.TeamName, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label>Country</label>
        @Html.EditorFor(a => a.CountryName, new { @class = "form-group", @placeholder = "Country" })
        @Html.ValidationMessageFor(a => a.CountryName, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label>Est. Date</label>
        @Html.EditorFor(a => a.DateOfBirth, new { @class = "form-group" })
        @Html.ValidationMessageFor(a => a.DateOfBirth, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label>Description</label>
        @Html.EditorFor(a => a.Decscript, new { @class = "form-group", @placeholder = "Introduce Yourself" })
        @Html.ValidationMessageFor(a => a.Decscript, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label>Verified Email</label>
        <div class="checkbox">
            @Html.EditorFor(a => a.IsEmailVerified, new { @class = "form-group" })
            @Html.ValidationMessageFor(a => a.IsEmailVerified, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label></label>
        <div class="checkbox">
            @Html.EditorFor(a => a.AdminType, new { @class = "form-group" })
            @Html.ValidationMessageFor(a => a.AdminType, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label>Eamil Subs</label>
        <div class="checkbox">
            @Html.EditorFor(a => a.SubEmail, new { @class = "form-group" })
            @Html.ValidationMessageFor(a => a.SubEmail, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-lg btn-success" href="javascript:document.getElementById('popupForm').submit()" />
    </div>
}